### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by xiaoxiangmoe** [mushan0x0/rc-form-hooks#12]
* [x]  isFieldTouched
* [x] isFieldsTouched
* [ ] isFieldValidating

**Comment by revskill10** [comment]
Any example of integrating with ant-design could be helpful also.

**Comment by damiangreen** [comment]
Previously I used validateFields((errors: any, values: ClockWidgetCustomData) => {
..

I don't see where errors are now in validateFields

**Comment by mushan0x0** [comment]
ref: https://github.com/mushan0x0/rc-form-hooks/commit/fcb14a1cae436e125acb1722835382d096c345a3

Features all are supported, please upgrade to the latest version.
