### ISSUE TITLE
The checkbox will not checked?

### ISSUE THREAD

**Issue by aldrich-xie** [mushan0x0/rc-form-hooks#26]
version:  0.0.1-alpha.23

I use checkbox in the form item, like the following code. When I click checkbox, it will not checked. 
```
<Form.Item>
      {getFieldDecorator('truncate', {valuePropName: 'checked'})(<Checkbox>test</Checkbox>)}
</Form.Item>
```

**Comment by mushan0x0** [comment]
Thank you, this issue has been fixed, please upgrade to the latest alpha.24
